# Generated by Django 3.2.4 on 2021-07-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='card_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
